- name: Prepare Palo Alto Firewall in Azure
  hosts: localhost
  gather_facts: no
  vars:
    azure_subscription_id: "{{ secrets.AZURE_SUBSCRIPTION_ID }}"
    azure_client_id: "{{ secrets.AZURE_CLIENT_ID }}"
    azure_secret: "{{ secrets.AZURE_SECRET }}"
    azure_tenant: "{{ secrets.AZURE_TENANT }}"
    palo_alto_ip: "{{ secrets.PALO_ALTO_IP }}"
    palo_alto_username: "{{ secrets.PALO_ALTO_USERNAME }}"
    palo_alto_password: "{{ secrets.PALO_ALTO_PASSWORD }}"
    strata_cloud_manager_fqdns:
      - "strata-cloud-manager.example.com"
    strata_cloud_manager_tcp_ports:
      - "443"
      - "3978"
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"
    mgmt_static_routes:
      - { network: "0.0.0.0/0", gateway: "10.0.0.1" }

  tasks:
    - name: Generate API key for Palo Alto firewall
      uri:
        url: "https://{{ palo_alto_ip }}/api/?type=keygen&user={{ palo_alto_username }}&password={{ palo_alto_password }}"
        method: GET
        validate_certs: no
        return_content: yes
      register: api_key_response

    - name: Extract API key from response
      set_fact:
        palo_alto_api_key: "{{ api_key_response.content | regex_search('<key>(.*)</key>', '\\1') }}"

    - name: Ensure Palo Alto firewall is reachable
      ping:

    - name: Configure management interface
      paloaltonetworks.panos.panos_interface:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        interface_name: "ethernet1/1"
        mode: "static"
        ip: "10.0.0.2"
        netmask: "255.255.255.0"
        commit: yes

    - name: Configure public interface
      paloaltonetworks.panos.panos_interface:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        interface_name: "ethernet1/2"
        mode: "static"
        ip: "192.168.1.2"
        netmask: "255.255.255.0"
        commit: yes

    - name: Configure private interface
      paloaltonetworks.panos.panos_interface:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        interface_name: "ethernet1/3"
        mode: "static"
        ip: "172.16.0.2"
        netmask: "255.255.255.0"
        commit: yes

    - name: Enable advanced routing
      paloaltonetworks.panos.panos_virtual_router:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        name: "default"
        interface:
          - "ethernet1/1"
          - "ethernet1/2"
          - "ethernet1/3"
        commit: yes

    - name: Configure DNS settings
      paloaltonetworks.panos.panos_dns:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        primary: "{{ dns_servers[0] }}"
        secondary: "{{ dns_servers[1] }}"
        commit: yes

    - name: Add static routes for management interface
      paloaltonetworks.panos.panos_static_route:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        name: "mgmt_route"
        destination: "{{ item.network }}"
        nexthop: "{{ item.gateway }}"
        interface: "ethernet1/1"
      loop: "{{ mgmt_static_routes }}"
      commit: yes

    - name: Allow Strata Cloud Manager FQDNs
      paloaltonetworks.panos.panos_address_object:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        name: "Strata_Cloud_Manager_FQDN"
        fqdn: "{{ item }}"
      loop: "{{ strata_cloud_manager_fqdns }}"
      commit: yes

    - name: Allow Strata Cloud Manager TCP ports
      paloaltonetworks.panos.panos_service_object:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        name: "Strata_Cloud_Manager_TCP"
        protocol: "tcp"
        destination_port: "{{ item }}"
      loop: "{{ strata_cloud_manager_tcp_ports }}"
      commit: yes

    - name: Generate CSR for device certificate
      paloaltonetworks.panos.panos_certificate:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        name: "Strata_Cloud_Manager_Cert"
        common_name: "palo_alto_firewall"
        country_name: "US"
        state_name: "California"
        locality_name: "San Jose"
        organization_name: "Palo Alto Networks"
        email: "admin@example.com"
        generate_csr: yes
        commit: yes

    - name: Import signed certificate
      paloaltonetworks.panos.panos_certificate:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        name: "Strata_Cloud_Manager_Cert"
        certificate: "{{ lookup('file', 'path/to/signed_certificate.crt') }}"
        private_key: "{{ lookup('file', 'path/to/private_key.key') }}"
        commit: yes

    - name: Onboard firewall to Strata Cloud Manager
      paloaltonetworks.panos.panos_cloud_services:
        ip_address: "{{ palo_alto_ip }}"
        api_key: "{{ palo_alto_api_key }}"
        cloud_services: "strata"
        certificate: "Strata_Cloud_Manager_Cert"
        commit: yes
